### ISSUE TITLE
Ionic 3 application in production using cordova-plugin-datecs-printer - Help

### ISSUE THREAD

**Issue by djasigner** [giorgiofellipe/cordova-plugin-datecs-printer#69]
Hello **@giorgiofellipe**, please could help to solve this problem, the application is working perfectly effect the bluetooth connection and it makes the impression OK.
My code:

```
public printText(){
    return new Promise((resolve, reject) => {
        DatecsPrinter.printText(text, charset, function () {
        	
       let alert = this.alertCtrl.create({
          title: 'Atenção!',
          subTitle: 'successfully completed',
          buttons: ['OK']
        });
        alert.present();

        }, function (error) {
       		alert("error");
        });
    }

```
**This way it does not work and I tried to call a method and it also does not work is it possible for me to execute something other than a simple _alert (), as in javascript_ once I send the data for printing?**

Thank you for the usual attention.

**Comment by giorgiofellipe** [comment]
Here goes an example of working service for Ionic3 written in typescript:

```typescript
import { Platform } from 'ionic-angular';
import { Injectable } from '@angular/core';

@Injectable()
export class PrinterService {
  private win: any;
  private defaultTimeout: Number = 100;

  constructor(private platform: Platform) {
    this.win = window;
    this.platform.ready().then(() => {
      if (this.win.cordova && !this.win.DatecsPrinter) {
        console.warn("DatecsPrinter plugin is missing. Have you installed the plugin? \nRun 'cordova plugin add cordova-plugin-datecs-printer'");
      }
    });
  }

  listBluetoothDevices() {
    return new Promise<any>((resolve, reject) => {
      this.win.DatecsPrinter.listBluetoothDevices((success) => resolve(success), (error) => reject(error));
    });
  }

  connect(deviceAddress: string): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      setTimeout(() => this.win.DatecsPrinter.connect(deviceAddress, (success) => resolve(success), (error) => reject(error)), this.defaultTimeout);
    });
  }

  disconnect(): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.win.DatecsPrinter.disconnect((success) => resolve(success), (error) => reject(error))
    });
  }

  feedPaper(lines: Number): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.win.DatecsPrinter.feedPaper(lines, (success) => resolve(success), (error) => reject(error));
    });
  }

  printText(text: string, charset: string = 'ISO-8859-1'): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.win.DatecsPrinter.printText(text, charset, (success) => resolve(success), (error) => reject(error));
    });
  }
}
```

**Comment by djasigner** [comment]
**Hello @giorgiofellipe**, thank you very much I even integrated printService and got ball show and is working as expected.
Your library is wonderful, congratulations to God for giving you many years of life.
I live in Brazil, in Bahia, I apologize for my English.
Anything will be at my disposal.

**Comment by giorgiofellipe** [comment]
Thanks mate!

**Comment by mtssangram** [comment]
Hello @giorgiofellipe,
Not working on ionic 4, When I try to add platform its give following error. If I remove plugin then platform added successfully 

ENOENT: no such file or directory, open ‘platforms/android/AndroidManifest.xml’

**Comment by CSR3Team** [comment]
when add cordova plugin add cordova-plugin-datecs-printer

is error

```
Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuild                                                                                                                er.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForS                                                                                                                plit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskActi                                                                                                                on(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(In                                                                                                                crementalTask.java:109)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                                sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.                                                                                                                run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De                                                                                                                faultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecuteAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecuteActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec                                                                                                                ute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingState                                                                                                                Executer.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut                                                                                                                e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu                                                                                                                ter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskE                                                                                                                xecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter                                                                                                                .execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut                                                                                                                e(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter                                                                                                                .execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.ex                                                                                                                ecute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De                                                                                                                faultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(Defau                                                                                                                ltTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTa                                                                                                                sk(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.                                                                                                                onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecu                                                                                                                torImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                .java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnabl                                                                                                                e.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.Executi                                                                                                                onException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for                                                                                                                 details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(Abstrac                                                                                                                tFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.j                                                                                                                ava:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(Ab                                                                                                                stractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuild                                                                                                                er.java:794)
        ... 47 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt                                                                                                                2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(Abstrac                                                                                                                tFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.j                                                                                                                ava:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(Ab                                                                                                                stractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValida                                                                                                                tedPackage$1(QueueableAapt2.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                .java:624)
        ... 1 more
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for d                                                                                                                etails
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutpu                                                                                                                t(AaptProcess.java:463)
:app:processDebugResources FAILED
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptPro                                                                                                                cess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProce                                                                                                                ss.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                 option to get more log output.

* Get more help at https://help.gradle.org

25 actionable tasks: 5 executed, 20 up-to-date
BUILD FAILED in 20s
cmd: Command failed with exit code 1 Error output:
C:\Users\Nuon Rathana\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.                                                                                                                0.aar\cdd3d8449eedd04a061e841479e7038d\res\values\values.xml:133:5-70: AAPT: err                                                                                                                or: resource android:attr/fontVariationSettings not found.

C:\Users\Nuon Rathana\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.                                                                                                                0.aar\cdd3d8449eedd04a061e841479e7038d\res\values\values.xml:133:5-70: AAPT: err                                                                                                                or: resource android:attr/ttcIndex not found.

D:\Mobile App\Ionic\Testing\printer\platforms\android\app\build\intermediates\in                                                                                                                cremental\mergeDebugResources\merged.dir\values\values.xml:87: error: resource a                                                                                                                ndroid:attr/fontVariationSettings not found.
D:\Mobile App\Ionic\Testing\printer\platforms\android\app\build\intermediates\in                                                                                                                cremental\mergeDebugResources\merged.dir\values\values.xml:87: error: resource a                                                                                                                ndroid:attr/ttcIndex not found.
error: failed linking references.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuild                                                                                                                er.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForS                                                                                                                plit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskActi                                                                                                                on(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(In                                                                                                                crementalTask.java:109)
        at sun.reflect.GeneratedMethodAccessor407.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                                sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore                                                                                                                $StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.                                                                                                                run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De                                                                                                                faultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecuteAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecuteActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex                                                                                                                ecute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec                                                                                                                ute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingState                                                                                                                Executer.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut                                                                                                                e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu                                                                                                                ter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskE                                                                                                                xecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter                                                                                                                .execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut                                                                                                                e(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter                                                                                                                .execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.ex                                                                                                                ecute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu                                                                                                                ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De                                                                                                                faultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul                                                                                                                tBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa                                                                                                                skWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(Defau                                                                                                                ltTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTa                                                                                                                sk(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo                                                                                                                rker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.                                                                                                                onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecu                                                                                                                torImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                .java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnabl                                                                                                                e.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.Executi                                                                                                                onException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for                                                                                                                 details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(Abstrac                                                                                                                tFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.j                                                                                                                ava:482)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(Ab                                                                                                                stractFuture.java:79)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuild                                                                                                                er.java:794)
        ... 47 more
Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt                                                                                                                2Exception: AAPT2 error: check logs for details
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(Abstrac                                                                                                                tFuture.java:503)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.j                                                                                                                ava:462)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(Ab                                                                                                                stractFuture.java:79)
        at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValida                                                                                                                tedPackage$1(QueueableAapt2.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                .java:624)
        ... 1 more
Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for d                                                                                                                etails
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutpu                                                                                                                t(AaptProcess.java:463)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptPro                                                                                                                cess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProce                                                                                                                ss.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                 option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
[ERROR] An error occurred while running subprocess cordova.

        cordova build android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more informa                                                                                                                tion.


```

**Comment by ezequiel88** [comment]
@CSR3Team  estou com o mesmo erro. Conseguiu resolver?

**Comment by 0luwaj0x1** [comment]
@CSR3Team were you able fix the build error ?
