### ISSUE TITLE
Can't make this work

### ISSUE THREAD

**Issue by leonardofmed** [giorgiofellipe/cordova-plugin-datecs-printer#80]
Quando tento rodar o app depois de instalar o `plugin` aparece o seguinte erro:

##
cp: copyFileSync: could not write to dest file (code=ENOENT):/home/leo/printer06/platforms/android/res/xml/config.xml

Parsing /home/leo/printer06/platforms/android/res/xml/config.xml failed
(node:5299) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/leo/printer06/platforms/android/res/xml/config.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.parseElementtreeSync (/home/leo/printer06/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new ConfigParser (/home/leo/printer06/platforms/android/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:30:24)
    at updateConfigFilesFrom (/home/leo/printer06/platforms/android/cordova/lib/prepare.js:106:18)
    at Api.module.exports.prepare (/home/leo/printer06/platforms/android/cordova/lib/prepare.js:42:20)
    at Api.prepare (/home/leo/printer06/platforms/android/cordova/Api.js:192:45)
    at /home/leo/.node/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:106:36
    at _fulfilled (/home/leo/.node/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/leo/.node/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:5299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##

Sendo que a pasta res do arquivo /home/leo/printer06/platforms/android/res/xml/config.xml não existe. Devo mover/copiar arquivos nessas pastas?

Existe um arquivo /home/leo/printer06/platforms/android/app/src/main/res/xml/config.xml . Se tento criar uma pasta onde estava dando o erro antes (home/leo/printer06/platforms/android/res/xml/) e colar esse arquivo um novo erro aparece se referindo à um outro arquivo "AndroidManifest.xml". Se copio esse arquivo para a pasta de erro e tento rodar o app, outro erro aparece e assim acontece várias vezes até dar um erro de BUILD FAILED.

**Comment by giorgiofellipe** [comment]
Poderia colar aqui a saída do seu `ionic info`?

**Comment by leonardofmed** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.4.0
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/leo/Android/Sdk

Misc:

    backend : pro

**Comment by giorgiofellipe** [comment]
Aparentemente é um problema dessa versão do cordova.
Você pode acompanhar a discussão e encontrar algumas soluções alternativas [aqui](https://github.com/ionic-team/ionic/issues/13702).
